@echo off

echo --[[ autogenerated ]]-->index
echo require("programs.none")>index

for %%a in (*.lua) do ( 
	if not "%%~na" == "index" (
		if not "%%~na" == "root" (
			if not "%%~na" == "none" (
				echo require("programs.%%~na"^)>>index
			)
		)
	)
)

copy index + index.prt index.lua
del index